@protocol = http://
@hostname = localhost
@port = 17763
@baseURL = {{protocol}}{{hostname}}:{{port}}

## Add Targets
POST {{baseURL}}/api/targets HTTP/1.1
content-type: application/json

{
    "url": "cmd/filetinder3.go"
}

### Get Targets
GET {{baseURL}}/api/targets HTTP/1.1
content-type: application/json

### Get Single Target
GET {{baseURL}}/api/targets/2 HTTP/1.1
content-type: application/json

### Get Single Target's File
GET {{baseURL}}/api/targets/2/file HTTP/1.1
content-type: application/json

### Get Single Target's Stat
GET {{baseURL}}/api/targets/2/fstats HTTP/1.1
content-type: application/json

### Delete Single Target
DELETE  {{baseURL}}/api/targets/2 HTTP/1.1
content-type: application/json

### Mark Single Target
POST {{baseURL}}/api/targets/1/mark HTTP/1.1
content-type: application/json

{
    "value": "remove"
}

### Get FileTinder server meta
GET {{baseURL}}/api/meta HTTP/1.1
content-type: application/json

### Invoke function to delete all marked files
POST {{baseURL}}/api/funcs/delete-all HTTP/1.1
content-type: application/json

### Invoke function to stop server
POST {{baseURL}}/api/funcs/stop-server HTTP/1.1
content-type: application/json